default:
  /login: "src/Template/login.php"
  /error_404: "src/Template/Error/Error404.php"

config:
  paramters: "config/parameters.php"

image:
  favicon: "assets/Image/TimeKeeper.png"

style:
  error: "assets/Style/error_default.css"
  login: "assets/Style/login.css"

js:
  route: ""

template:
  login: "src/Template/login.php"

service:
  auth: "src/Service/AuthService/AuthService.php"
