default:
  /redirect: "src/redirect.php"
  /login: "src/Template/login.php"
  /error: "src/Template/error.php"
  /login_authorization: "src/Listener/loginAuthorization.php"

config:
  parameters: "config/parameters.yaml"

image:
  favicon: "http://tk.localhost/assets/Image/TimeKeeper.png"

style:
  error: "http://tk.localhost/assets/Style/error.css"
  login: "assets/Style/login.css"

js:
  login: "assets/src/login.js"
  error: "assets/src/error.js"

#template:

service:
  auth: "src/Service/AuthService.php"
  db: "src/Service/DatabaseService.php"
  error: "src/Service/ErrorService.php"
