default:
  /error: "src/View/error.php"
  /login: "src/View/login.php"
  /main: "src/View/main/main.php"

api:
  controller: "src/API/ApiController.php"
  loginAction: "src/API/ApiActions/Authorization/loginAction.php"
  logoutAction: "src/API/ApiActions/Authorization/logoutAction.php"
  startAction: "src/API/ApiActions/Console/startAction.php"
  breakAction: "src/API/ApiActions/Console/breakAction.php"
  stopAction: "src/API/ApiActions/Console/stopAction.php"
  getWorkdaysAction: "src/API/ApiActions/Workday/getWorkdaysAction.php"
  getWorkdayAction: "src/API/ApiActions/Workday/getWorkdayAction.php"

config:
  parameters: "config/parameters.yaml"

image:
  favicon: "assets/Image/TimeKeeper.png"

js:
  console: "assets/src/console.js"
  error: "assets/src/error.js"
  login: "assets/src/login.js"
  main: "assets/src/main.js"
  session_timout: "assets/src/sessionTimeout.js"
  utility: "assets/src/utility.js"

listener:
  api: "src/Listener/apiListener.php"
  session_checker: "src/Listener/sessionLifespanListener.php"

service:
  db: "src/Service/DatabaseService.php"
  error: "src/Service/ErrorService.php"

style:
  console: "assets/Style/console.css"
  error: "assets/Style/error.css"
  login: "assets/Style/login.css"
  main: "assets/Style/main.css"

view:
  console: "src/View/main/console.html"
  head: "src/View/head.php"
  table: "src/View/main/table.php"
  row: "src/View/main/row.php"

vendor:
  jquery: "vendor/jquery-3.6.0.min.js"
